version: '3.2'
services:
  php:
    build:
      context: ./php
      args:
        PHP_IMAGE: ${PHP_IMAGE}
    ports:
      - "${PHP_FPM_PORT}:9000"
    environment:
      - TZ=${TZ}
    volumes:
      - ${WWW_LOCAL_DIR}:/data/www:rw
      - ${PHP_CONF}:/usr/local/etc:rw
    working_dir: /data/www
    restart: always
    command: php-fpm