version: '3.2'
services:
  mysql:
    build:
      context: ./mysql
      args:
        MYSQL_IMAGE: ${MYSQL_IMAGE}
    expose:
      - ${MYSQL_PORT}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ${MYSQL_DATA}:/var/lib/mysql
      - ${MYSQL_CONF}:/etc/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: ${TZ}
    restart: always
    command: --character-set-server=utf8



