version: '3.2'
services:
  redis:
    build:
      context: ./redis
      args:
        - REDIS_IMAGE=${REDIS_IMAGE}
        - TZ=${TZ}
    ports:
      - "${REDIS_PORT}:6379"
#    volumes:
#      - ./redis/data:/data
#      - ./redis/logs:/var/lib/redis-logs:rw
#      - ./redis/redis.conf:/etc/redis.conf
    restart: always



