version: '3.2'
services:
  nginx:
    build:
      context: ./nginx
      args:
        - NGINX_IMAGE=${NGINX_IMAGE}
    volumes:
      - ${WWW_LOCAL_DIR}:/data/www
      - ${NGINX_LOG}:/var/log/nginx
      - ${NGINX_CONF}:/etc/nginx/nginx.conf
      - ${NGINX_VHOST}:/etc/nginx/conf.d
    working_dir: /data/www
    expose:
      - ${NGINX_HTTP_PORT}
      - ${NGINX_HTTPS_PORT}
    ports:
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"
    restart: always
    command: nginx-debug -g 'daemon off;'