version: '3.2'
services:
  nginx:
    build: ./nginx
    container_name: mynginx
    volumes:
      - ./data/www:/data/www
      - ./data/logs/nginx:/var/log/nginx
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "81:80"
      - "444:443"
    restart: always
    command: nginx -g 'daemon off;'

  redis:
    build: ./redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis/dbdata:/data
      - ./data/logs/redis:/var/lib/redis-logs:rw
      - ./redis/redis.conf:/etc/redis.conf
    restart: always

