version: '3.2'
services:
  php:
    build: ./php
    ports:
      - "9000:9000"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./data/www:/data/www:rw
      - ./php/conf:/usr/local/etc:rw
    working_dir: /data/www
    restart: always
    command: php-fpm

  nginx:
    build: ./nginx
#    depends_on:
#      - php
    volumes:
      - ./data/www:/data/www
      - ./nginx/logs:/var/log/nginx
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf/vhost:/etc/nginx/conf.d
    working_dir: /data/www
    expose:
      - "80"
      - "443"
    ports:
      - "81:80"
      - "443:443"
    restart: always
    command: nginx-debug -g 'daemon off;'

  mysql:
    build: ./mysql
    expose:
      - "3307"
    ports:
      - "3307:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf:/etc/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      TZ: "Asia/Shanghai"
    restart: always
    command: --character-set-server=utf8



