version: '3.2'
services:
  php-fpm:
    container_name: myphp
    build: ./php
    ports:
      - "9000:9000"
    links:
      - mysql-db:mysql-db
      - redis-db:redis-db
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./data/www:/data/www:rw
      - ./data/logs/php/php-fpm.log:/var/log/php-fpm:rw
      - ./php/conf:/usr/local/php/etc:ro
    restart: always
    command: php-fpm

  nginx:
    build: ./nginx
    depends_on:
      - php-fpm
    links:
      - php-fpm:php-fpm
    volumes:
      - ./data/www:/data/www
      - ./data/logs/nginx:/var/log/nginx
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    restart: always
    command: nginx -g 'daemon off;'

  mysql-db:
    image: "mysql:5.7"
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql/dbdata:/var/lib/mysql:rw
      - ./data/logs/mysql/mysql.log:/var/lib/mysql-logs:rw
      - ./mysql/conf:/etc/mysql/conf.d:ro
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: zphaldb
      MYSQL_USER: zphal
      MYSQL_PASSWORD: zphal123
    restart: always
    command: "--character-set-server=utf8"

  redis-db:
    build: ./redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis/dbdata:/data
      - ./data/logs/redis:/var/lib/redis-logs:rw
      - ./redis/redis.conf:/etc/redis.conf
    restart: always

